# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rami/hazel-kernel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rami/hazel-kernel

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rami/hazel-kernel/CMakeFiles /home/rami/hazel-kernel//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rami/hazel-kernel/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kernel

# Build rule for target.
kernel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kernel
.PHONY : kernel

# fast build rule for target.
kernel/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/build
.PHONY : kernel/fast

#=============================================================================
# Target rules for targets named iso

# Build rule for target.
iso: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 iso
.PHONY : iso

# fast build rule for target.
iso/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso.dir/build.make CMakeFiles/iso.dir/build
.PHONY : iso/fast

#=============================================================================
# Target rules for targets named init-mod

# Build rule for target.
init-mod: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 init-mod
.PHONY : init-mod

# fast build rule for target.
init-mod/fast:
	$(MAKE) $(MAKESILENT) -f init-mod/CMakeFiles/init-mod.dir/build.make init-mod/CMakeFiles/init-mod.dir/build
.PHONY : init-mod/fast

src/arch/i686/allocator.obj: src/arch/i686/allocator.c.obj
.PHONY : src/arch/i686/allocator.obj

# target to build an object file
src/arch/i686/allocator.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/allocator.c.obj
.PHONY : src/arch/i686/allocator.c.obj

src/arch/i686/allocator.i: src/arch/i686/allocator.c.i
.PHONY : src/arch/i686/allocator.i

# target to preprocess a source file
src/arch/i686/allocator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/allocator.c.i
.PHONY : src/arch/i686/allocator.c.i

src/arch/i686/allocator.s: src/arch/i686/allocator.c.s
.PHONY : src/arch/i686/allocator.s

# target to generate assembly for a file
src/arch/i686/allocator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/allocator.c.s
.PHONY : src/arch/i686/allocator.c.s

src/arch/i686/bootstrap.obj: src/arch/i686/bootstrap.c.obj
.PHONY : src/arch/i686/bootstrap.obj

# target to build an object file
src/arch/i686/bootstrap.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/bootstrap.c.obj
.PHONY : src/arch/i686/bootstrap.c.obj

src/arch/i686/bootstrap.i: src/arch/i686/bootstrap.c.i
.PHONY : src/arch/i686/bootstrap.i

# target to preprocess a source file
src/arch/i686/bootstrap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/bootstrap.c.i
.PHONY : src/arch/i686/bootstrap.c.i

src/arch/i686/bootstrap.s: src/arch/i686/bootstrap.c.s
.PHONY : src/arch/i686/bootstrap.s

# target to generate assembly for a file
src/arch/i686/bootstrap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/bootstrap.c.s
.PHONY : src/arch/i686/bootstrap.c.s

src/arch/i686/exception.obj: src/arch/i686/exception.c.obj
.PHONY : src/arch/i686/exception.obj

# target to build an object file
src/arch/i686/exception.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/exception.c.obj
.PHONY : src/arch/i686/exception.c.obj

src/arch/i686/exception.i: src/arch/i686/exception.c.i
.PHONY : src/arch/i686/exception.i

# target to preprocess a source file
src/arch/i686/exception.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/exception.c.i
.PHONY : src/arch/i686/exception.c.i

src/arch/i686/exception.s: src/arch/i686/exception.c.s
.PHONY : src/arch/i686/exception.s

# target to generate assembly for a file
src/arch/i686/exception.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/exception.c.s
.PHONY : src/arch/i686/exception.c.s

src/arch/i686/interrupts.obj: src/arch/i686/interrupts.c.obj
.PHONY : src/arch/i686/interrupts.obj

# target to build an object file
src/arch/i686/interrupts.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/interrupts.c.obj
.PHONY : src/arch/i686/interrupts.c.obj

src/arch/i686/interrupts.i: src/arch/i686/interrupts.c.i
.PHONY : src/arch/i686/interrupts.i

# target to preprocess a source file
src/arch/i686/interrupts.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/interrupts.c.i
.PHONY : src/arch/i686/interrupts.c.i

src/arch/i686/interrupts.s: src/arch/i686/interrupts.c.s
.PHONY : src/arch/i686/interrupts.s

# target to generate assembly for a file
src/arch/i686/interrupts.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/interrupts.c.s
.PHONY : src/arch/i686/interrupts.c.s

src/arch/i686/io.obj: src/arch/i686/io.c.obj
.PHONY : src/arch/i686/io.obj

# target to build an object file
src/arch/i686/io.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/io.c.obj
.PHONY : src/arch/i686/io.c.obj

src/arch/i686/io.i: src/arch/i686/io.c.i
.PHONY : src/arch/i686/io.i

# target to preprocess a source file
src/arch/i686/io.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/io.c.i
.PHONY : src/arch/i686/io.c.i

src/arch/i686/io.s: src/arch/i686/io.c.s
.PHONY : src/arch/i686/io.s

# target to generate assembly for a file
src/arch/i686/io.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/io.c.s
.PHONY : src/arch/i686/io.c.s

src/arch/i686/multiboot.obj: src/arch/i686/multiboot.S.obj
.PHONY : src/arch/i686/multiboot.obj

# target to build an object file
src/arch/i686/multiboot.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/multiboot.S.obj
.PHONY : src/arch/i686/multiboot.S.obj

src/arch/i686/pic.obj: src/arch/i686/pic.c.obj
.PHONY : src/arch/i686/pic.obj

# target to build an object file
src/arch/i686/pic.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/pic.c.obj
.PHONY : src/arch/i686/pic.c.obj

src/arch/i686/pic.i: src/arch/i686/pic.c.i
.PHONY : src/arch/i686/pic.i

# target to preprocess a source file
src/arch/i686/pic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/pic.c.i
.PHONY : src/arch/i686/pic.c.i

src/arch/i686/pic.s: src/arch/i686/pic.c.s
.PHONY : src/arch/i686/pic.s

# target to generate assembly for a file
src/arch/i686/pic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/pic.c.s
.PHONY : src/arch/i686/pic.c.s

src/arch/i686/pit.obj: src/arch/i686/pit.c.obj
.PHONY : src/arch/i686/pit.obj

# target to build an object file
src/arch/i686/pit.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/pit.c.obj
.PHONY : src/arch/i686/pit.c.obj

src/arch/i686/pit.i: src/arch/i686/pit.c.i
.PHONY : src/arch/i686/pit.i

# target to preprocess a source file
src/arch/i686/pit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/pit.c.i
.PHONY : src/arch/i686/pit.c.i

src/arch/i686/pit.s: src/arch/i686/pit.c.s
.PHONY : src/arch/i686/pit.s

# target to generate assembly for a file
src/arch/i686/pit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/pit.c.s
.PHONY : src/arch/i686/pit.c.s

src/arch/i686/start.obj: src/arch/i686/start.S.obj
.PHONY : src/arch/i686/start.obj

# target to build an object file
src/arch/i686/start.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/start.S.obj
.PHONY : src/arch/i686/start.S.obj

src/arch/i686/syscall.obj: src/arch/i686/syscall.c.obj
.PHONY : src/arch/i686/syscall.obj

# target to build an object file
src/arch/i686/syscall.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/syscall.c.obj
.PHONY : src/arch/i686/syscall.c.obj

src/arch/i686/syscall.i: src/arch/i686/syscall.c.i
.PHONY : src/arch/i686/syscall.i

# target to preprocess a source file
src/arch/i686/syscall.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/syscall.c.i
.PHONY : src/arch/i686/syscall.c.i

src/arch/i686/syscall.s: src/arch/i686/syscall.c.s
.PHONY : src/arch/i686/syscall.s

# target to generate assembly for a file
src/arch/i686/syscall.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/syscall.c.s
.PHONY : src/arch/i686/syscall.c.s

src/arch/i686/uart.obj: src/arch/i686/uart.c.obj
.PHONY : src/arch/i686/uart.obj

# target to build an object file
src/arch/i686/uart.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/uart.c.obj
.PHONY : src/arch/i686/uart.c.obj

src/arch/i686/uart.i: src/arch/i686/uart.c.i
.PHONY : src/arch/i686/uart.i

# target to preprocess a source file
src/arch/i686/uart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/uart.c.i
.PHONY : src/arch/i686/uart.c.i

src/arch/i686/uart.s: src/arch/i686/uart.c.s
.PHONY : src/arch/i686/uart.s

# target to generate assembly for a file
src/arch/i686/uart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/uart.c.s
.PHONY : src/arch/i686/uart.c.s

src/arch/i686/user.obj: src/arch/i686/user.c.obj
.PHONY : src/arch/i686/user.obj

# target to build an object file
src/arch/i686/user.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/user.c.obj
.PHONY : src/arch/i686/user.c.obj

src/arch/i686/user.i: src/arch/i686/user.c.i
.PHONY : src/arch/i686/user.i

# target to preprocess a source file
src/arch/i686/user.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/user.c.i
.PHONY : src/arch/i686/user.c.i

src/arch/i686/user.s: src/arch/i686/user.c.s
.PHONY : src/arch/i686/user.s

# target to generate assembly for a file
src/arch/i686/user.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/arch/i686/user.c.s
.PHONY : src/arch/i686/user.c.s

src/kmain.obj: src/kmain.c.obj
.PHONY : src/kmain.obj

# target to build an object file
src/kmain.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kmain.c.obj
.PHONY : src/kmain.c.obj

src/kmain.i: src/kmain.c.i
.PHONY : src/kmain.i

# target to preprocess a source file
src/kmain.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kmain.c.i
.PHONY : src/kmain.c.i

src/kmain.s: src/kmain.c.s
.PHONY : src/kmain.s

# target to generate assembly for a file
src/kmain.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kmain.c.s
.PHONY : src/kmain.c.s

src/printf.obj: src/printf.c.obj
.PHONY : src/printf.obj

# target to build an object file
src/printf.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/printf.c.obj
.PHONY : src/printf.c.obj

src/printf.i: src/printf.c.i
.PHONY : src/printf.i

# target to preprocess a source file
src/printf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/printf.c.i
.PHONY : src/printf.c.i

src/printf.s: src/printf.c.s
.PHONY : src/printf.s

# target to generate assembly for a file
src/printf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/printf.c.s
.PHONY : src/printf.c.s

src/process.obj: src/process.c.obj
.PHONY : src/process.obj

# target to build an object file
src/process.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/process.c.obj
.PHONY : src/process.c.obj

src/process.i: src/process.c.i
.PHONY : src/process.i

# target to preprocess a source file
src/process.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/process.c.i
.PHONY : src/process.c.i

src/process.s: src/process.c.s
.PHONY : src/process.s

# target to generate assembly for a file
src/process.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/process.c.s
.PHONY : src/process.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... iso"
	@echo "... init-mod"
	@echo "... kernel"
	@echo "... src/arch/i686/allocator.obj"
	@echo "... src/arch/i686/allocator.i"
	@echo "... src/arch/i686/allocator.s"
	@echo "... src/arch/i686/bootstrap.obj"
	@echo "... src/arch/i686/bootstrap.i"
	@echo "... src/arch/i686/bootstrap.s"
	@echo "... src/arch/i686/exception.obj"
	@echo "... src/arch/i686/exception.i"
	@echo "... src/arch/i686/exception.s"
	@echo "... src/arch/i686/interrupts.obj"
	@echo "... src/arch/i686/interrupts.i"
	@echo "... src/arch/i686/interrupts.s"
	@echo "... src/arch/i686/io.obj"
	@echo "... src/arch/i686/io.i"
	@echo "... src/arch/i686/io.s"
	@echo "... src/arch/i686/multiboot.obj"
	@echo "... src/arch/i686/pic.obj"
	@echo "... src/arch/i686/pic.i"
	@echo "... src/arch/i686/pic.s"
	@echo "... src/arch/i686/pit.obj"
	@echo "... src/arch/i686/pit.i"
	@echo "... src/arch/i686/pit.s"
	@echo "... src/arch/i686/start.obj"
	@echo "... src/arch/i686/syscall.obj"
	@echo "... src/arch/i686/syscall.i"
	@echo "... src/arch/i686/syscall.s"
	@echo "... src/arch/i686/uart.obj"
	@echo "... src/arch/i686/uart.i"
	@echo "... src/arch/i686/uart.s"
	@echo "... src/arch/i686/user.obj"
	@echo "... src/arch/i686/user.i"
	@echo "... src/arch/i686/user.s"
	@echo "... src/kmain.obj"
	@echo "... src/kmain.i"
	@echo "... src/kmain.s"
	@echo "... src/printf.obj"
	@echo "... src/printf.i"
	@echo "... src/printf.s"
	@echo "... src/process.obj"
	@echo "... src/process.i"
	@echo "... src/process.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

