set(CMAKE_SYSTEM_NAME Generic-ELF)
set(ARCH i686)
set(CXX i686-elf-g++)
set(CMAKE_CXX_COMPILER ${CXX})
set(CMAKE_CXX_FLAGS "-ffreestanding -Wall -Wextra -Werror -g")
set(CMAKE_EXE_LINKER_FLAGS "-ffreestanding -nostdlib -T ${CMAKE_CURRENT_SOURCE_DIR}/src/arch/${ARCH}/linker.ld")
